### ISSUE TITLE
EMMC partition?

### ISSUE THREAD

**Issue by zhangn1985** [150balbes/Build-Armbian#8]
hi, I find https://github.com/150balbes/Build-Armbian/blob/master/packages/bsp/aml-s9xxx/install.sh

the first thing you did in this script is backup default uboot, why not mainline uboot, or uboot build from khadas uboot repo? and you restore it to /dev/mmcblk1, why doesn't it break your new partition table?

you use partd to partition EMMC, set partition type to msdos, and first partition if fat32 start at 700M, size 128M. could you tell me why start at 700M? this partition is for boot?

could uboot recognize this new partition table? I find in khadas's kernel repo, it has a partition.dtb, why this different?

**Comment by 150balbes** [comment]
> why not mainline uboot, or uboot build from khadas uboot repo?

Because u-boot-2018 or khadas cannot work on all models on which the installation is performed. The most correct u-boot is u-boot which is supplied by the manufacturer of this TV box, it takes into account all the nuances of the equipment.



> and you restore it to /dev/mmcblk1, why doesn't it break your new partition table?

Because it is properly restored (this is my "know-how" :) ).



> could you tell me why start at 700M? this partition is for boot?

Because in the first 700Mb is all important for the TV box information from the standard firmware (u-boot recovery env boot etc). These data, if necessary, allow you to always restore the TV box to its original state using standard tools USB Birn Tool.



> could uboot recognize this new partition table? I find in khadas's kernel repo, it has a partition.dtb, why this different?

Because what is described in this file is not a Linux partition, it is a special EMMC memory partition for Android format.

**Comment by zhangn1985** [comment]
exclude first 700M is reserved for standard USB burn tool, the others are free to repartition, is there a backup partition table in default-uboot which make first 700M accessible?
